apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: gateway-web
  name: gateway-web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway-web
    spec:
      containers:
      - image: eu.gcr.io/bagpipescores/bagpipe-scores:latest
        name: gateway-web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
