apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: lilypond-web
  name: lilypond-web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: lilypond-web
    spec:
      containers:
      - image: eu.gcr.io/bagpipescores/lilypond-api:latest
        name: lilypond-web
        resources: {}
      restartPolicy: Always
status: {}
